project_id = "bajnlawcjididzylglog"

[functions.generate-content]
verify_jwt = false

[functions.parse-content]
verify_jwt = false

[functions.export-content]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.export-quiz]
verify_jwt = false

[functions.generate-kudos]
verify_jwt = false
